spring:
    datasource:
        className: com.mysql.jdbc.Driver
        password:
        platform: mysql
        url: jdbc:mysql://localhost/testando_teste?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
        name: ticket-serve


eureka:
    client:
        service-url:
            default-zone: ${EUREKA_URI:http://localhost:8762}
    instance:
        prefer-ip-address: true


server:
    port: 8081
#@Bean
#public FilterRegistrationBean corsFilter() {
#UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
#CorsConfiguration config = new CorsConfiguration();
#config.setAllowCredentials(true);
#config.addAllowedOrigin("*");
#config.addAllowedHeader("*");
#config.addAllowedMethod("*");
#source.registerCorsConfiguration("/**", config);
#FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
#bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
#return bean;
#}
#
#}