spring:
    datasource:
        className: com.mysql.jdbc.Driver
        password:
        platform: mysql
        url: jdbc:mysql://localhost/testando_teste?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
        name: product-serve


eureka:
    client:
        service-url:
            default-zone: ${EUREKA_URI:http://localhost:8761}
    instance:
        prefer-ip-address: true

server:
    port: 8082